#!/usr/bin/env zsh
# script to obatin machine's ip and run the docker container
ip=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')
xhost + $ip
echo 'checking redis ...'
state=$(docker container inspect -f '{{.State.Status}}' this_redis) 
echo "$state"
if  [ $state = "exited" ]; then 
	echo 'starting redis'
	docker start this_redis
elif [ $state = "running" ]; then 
	echo 'stopping redis...'
	docker stop  this_redis
	docker start this_redis 	
else
 	docker run -d --name this_redis redis
fi

# scientific
echo 'running scientific-emacs:0.1'
docker run --rm -it \
-v `pwd`/config:/root \
-v `pwd`:/home \
-e DISPLAY=$ip:0 \
-v /tmp/.X11-unix:/tmp/.X11-unix \
--link this_redis \
gmarxcc/scientific-emacs:0.1
# end
