#!/usr/bin/env zsh
# scriipt to obatin machine's ip and run the docker container
ip=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')
xhost + $ip
echo 'running scientific-emacs:0.1'
docker run --rm -it \
	-v `pwd`/config:/root \
        -v `pwd`:/home\
        -e DISPLAY=$ip:0 \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
	--link this_redis \
        gmarxcc/scientific-emacs:0.1
